version: '3.0'
services:
  app:
    container_name: app
    depends_on:
      - database
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    working_dir: /src
    volumes:
      - .:/src  
  database:
    container_name: database
    image: mongo:4.2
    restart: always
    ports:
      - '27017:27017'
    volumes: 
      - ./data:/data/db